# This is used to verify that a container image has the basic expected behavior.
# See https://github.com/NVIDIA/container-canary
#
# Run locally like:
#
# canary validate --file canary-validator.yml ghcr.io/bluesky/tiled:latest

apiVersion: container-canary.nvidia.com/v2
kind: Validator
name: tiled
description: Validate that Tiled container image is operational.
env:
 - name: TILED_SINGLE_USER_API_KEY
   value: secret
ports:
 - port: 8000
   protocol: TCP
volumes: []
checks:
 - name: http
   description: Exposes an HTTP interface on port 8000
   probe:
     httpGet:
       path: /
       port: 8000
     initialDelaySeconds: 5
     timeoutSeconds: 10
     failureThreshold: 3
 - name: http
   description: Serves a REST API with a public endpoint /api/v1
   probe:
     httpGet:
       path: /api/v1
       port: 8000
     initialDelaySeconds: 5
     timeoutSeconds: 10
     failureThreshold: 3
 - name: http
   description: Serves a REST API with an authenticated endpoint /api/v1/search
   probe:
     httpGet:
       path: /api/v1
       port: 8000
     initialDelaySeconds: 5
     timeoutSeconds: 10
     failureThreshold: 3
     httpHeaders:
      - name: Authorization
        value: Apikey secret
 - name: http
   description: Serves a UI at /ui/browse
   probe:
     httpGet:
       path: /ui/browse
       port: 8000
     initialDelaySeconds: 5
     timeoutSeconds: 10
     failureThreshold: 3
     httpHeaders:
      - name: Authorization
        value: Apikey secret
