---
services:
  tiled:
    build:
      context: .
      dockerfile: Containerfile
    environment:
      - TILED_SINGLE_USER_API_KEY=${TILED_SINGLE_USER_API_KEY}
      - TILED_CATALOG_URI=postgresql://tiled:${POSTGRES_PASSWORD}@postgres:5432/tiled_catalog
      - TILED_CATALOG_WRITABLE_STORAGE=["file:///storage", "postgresql://tiled:${POSTGRES_PASSWORD}@postgres:5432/tiled_storage"]
      - TILED_STREAMING_CACHE_URI=redis://:${REDIS_PASSWORD}@redis:6379
      - TILED_WEBHOOKS_SECRET_KEYS=${TILED_WEBHOOKS_SECRET_KEYS:-}
      - TILED_WEBHOOKS_ALLOW_HTTP=${TILED_WEBHOOKS_ALLOW_HTTP:-false}
      - TILED_WEBHOOKS_ALLOW_PRIVATE_ADDRESSES=${TILED_WEBHOOKS_ALLOW_PRIVATE_ADDRESSES:-false}
    volumes:
      - tiled_data:/storage
    ports:
      - 8000:8000
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
      test: curl --fail http://localhost:8000/healthz || exit 1
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  postgres:
    image: docker.io/postgres:16
    environment:
      - POSTGRES_USER=tiled
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # We create two databases, 'tiled_catalog' (metadata) and
      # 'tiled_storage' (tabular data) below. But it is required to
      # specify one here, so we use 'postgres' as a neutral default.
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: pg_isready -U tiled -d postgres
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: docker.io/redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: redis-cli -a ${REDIS_PASSWORD} ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  tiled_data:
  postgres_data:
  redis_data:

networks:
  backend: {}
