version: "3.2"
services:
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data --console-address :9001
    restart: unless-stopped
  create-bucket:
    image: minio/mc:latest
    environment:
      MC_HOST_minio: http://minioadmin:minioadmin@minio:9000
    entrypoint:
      - sh
      - -c
      - |
        until mc ls minio > /dev/null 2>&1; do
          sleep 0.5
        done

        mc mb --ignore-existing minio/buck
volumes:
  minio-data:
