specs:
  - spec: CatalogOfBlueskyRuns
    columns:
      - header: Bluesky Plan
        select_metadata: start.plan_name
        field: plan_name
      - header: Scan ID
        select_metadata: start.scan_id
        field: scan_id
      - header: Time
        select_metadata: start.time
        field: start_time
    default_columns:
      - plan_name
      - scan_id
structure_families:
  array:
    formats:
      - mimetype: text/csv
        display_name: CSV
        extension: .csv
      - mimetype: text/plain
        display_name: Text
        extension: .txt
      - mimetype: image/png
        display_name: PNG image
        extension: .png
      - mimetype: image/tiff
        display_name: TIFF image
        extension: .tiff
      - mimetype: application/json
        display_name: JSON
        extension: .json
      - mimetype: application/json-seq
        display_name: JSON Lines
        extension: .jsonl
      - mimetype: text/html
        display_name: HTML
        extension: .html
      - mimetype: application/octet-stream
        display_name: C-ordered array
        extension: ""
  dataframe:
    formats:
      - mimetype: text/csv
        display_name: CSV
        extension: .csv
      - mimetype: text/plain
        display_name: Text
        extension: .txt
      - mimetype: application/vnd.apache.arrow.file
        display_name: Apache Arrow
        extension: ""
      - mimetype: application/x-parquet
        display_name: Parquet
        extension: .parquet
      - mimetype: application/json
        display_name: JSON
        extension: .json
      - mimetype: application/json-seq
        display_name: JSON Lines
        extension: .jsonl
      - mimetype: text/html
        display_name: HTML
        extension: .html
  xarray_dataset:
    formats:
      - mimetype: application/x-hdf
        display_name: HDF5
        extension: .h5
  node:
    formats:
      - mimetype: application/x-hdf
        display_name: HDF5
        extension: .h5
