# config.yml
trees:
  - path: /
    tree:
      type: tiled.examples.generated_minimal:tree
uvicorn:
  host: 0.0.0.0
  port: 8000
database:
  uri: /tmp/tiled_database.sqlite  # This is not actually created by test.
allow_anonymous_access: true
providers:
- provider: test
  authenticator:
    type: tiled.authenticators:DictionaryAuthenticator
    users_to_passwords:
      alice: secret1
      bob: secret2
      cara: secret3
