authentication:
  providers:
  - provider: keycloak_oidc
    authenticator: tiled.authenticators:ProxiedOIDCAuthenticator
    args:
      audience: tiled_aud
      client_id: tiled
      device_flow_client_id: tiled-cli
      well_known_uri: "http://localhost:8080/realms/master/.well-known/openid-configuration"
      scopes:
        - openid
        - email
        - profile
      confirmation_message: "You have logged in with Proxied OIDC as {id}."

access_control:
  access_policy: "tiled.access_control.access_policies:ExternalPolicyDecisionPoint"
  args:
    authorization_provider: http://localhost:8181/v1/data/rbac/allow
    audience: tiled_aud
    attribute: permission

trees:
 # Just some arbitrary example data...
 # The point of this example is the authenticaiton above.
 - tree: example_configs.keycloak_oidc.example_data:tree
   path: /
