"""
Built-in serializer for the XAS Data Interchange (XDI) format.

Spec: https://github.com/XraySpectroscopy/XAS-Data-Interchange/blob/master/specification/spec.md

This serializer is registered under the spec name "xdi" (resolved at dispatch time to
StructureFamily.container) so it only activates for datasets explicitly tagged with
Spec("xdi", ...).

Because the XDI spec applies at the scan/container level (the spec tag lives on the
container node, not on a child table), the serializer receives a container node and
filter_for_access callable, walks the node to find the first table child, reads it,
and writes the XDI file using the container's own metadata.

The expected metadata structure mirrors that produced by tiled.examples.xdi.XDIAdapter:

    metadata = {
        "xdi_version": "1.0",
        "extra_version": "GSE/1.0",  # optional
        "fields": {
            "Element": {"symbol": "Cu", "edge": "K"},
            "Mono": {"d_spacing": "3.13553"},
            ...
        },
        "comments": "# optional free-form text\\n",  # optional
    }

The MIME type is "application/x-xdi" and the file extension alias ".xdi" is registered.
"""

import io
import mimetypes

from ..media_type_registration import default_serialization_registry
from ..structures.core import StructureFamily
from ..utils import ensure_awaitable

# Register ".xdi" extension -> "application/x-xdi"
mimetypes.types_map.setdefault(".xdi", "application/x-xdi")

# XDI-defined namespaces (from the specification dictionary).
# Used as a lookup table to validate / prioritise known fields when writing.
XDI_DEFINED_NAMESPACES = {
    "Facility": {"name", "energy", "current", "xray_source"},
    "Beamline": {"name", "collimation", "focusing", "harmonic_rejection"},
    "Mono": {"name", "d_spacing"},
    "Detector": {"i0", "it", "if", "ir"},
    "Sample": {
        "name",
        "id",
        "stoichiometry",
        "prep",
        "experimenters",
        "temperature",
    },
    "Scan": {"start_time", "end_time", "edge_energy"},
    "Element": {"symbol", "edge", "reference", "ref_edge"},
    "Column": set(),  # Column tags are integers; all are valid
}

# Required fields per the XDI spec
XDI_REQUIRED_FIELDS = {
    "Element": {"symbol", "edge"},
    "Mono": {"d_spacing"},
}


def _write_xdi(df, metadata):
    """Format a DataFrame and XDI metadata dict into XDI file bytes.

    Parameters
    ----------
    df : pandas.DataFrame
        The data table. The first column should be the energy/abscissa array.
    metadata : dict
        Must contain "fields": dict of {namespace: {tag: value}}.
        May optionally contain "xdi_version", "extra_version", "comments".

    Returns
    -------
    bytes
        UTF-8 encoded XDI file content.
    """
    output = io.StringIO()

    # --- Version line (required, must be first) ---
    xdi_version = metadata.get("xdi_version") or "1.0"
    extra_version = metadata.get("extra_version") or ""
    version_line = f"# XDI/{xdi_version}"
    if extra_version:
        version_line += f" {extra_version}"
    output.write(version_line + "\n")

    # --- Header fields ---
    # Write defined namespaces first (in spec-recommended order), then extensions.
    fields = metadata.get("fields", {})

    def _write_namespace(namespace, tags):
        for tag, value in tags.items():
            output.write(f"# {namespace}.{tag}: {value}\n")

    defined_order = list(XDI_DEFINED_NAMESPACES.keys())
    written_namespaces = set()

    for namespace in defined_order:
        if namespace in fields:
            _write_namespace(namespace, fields[namespace])
            written_namespaces.add(namespace)

    # Write any extension (non-defined) namespaces afterwards
    for namespace, tags in fields.items():
        if namespace not in written_namespaces:
            _write_namespace(namespace, tags)

    # --- Field-end separator (always present, per spec) ---
    output.write("# /////////////\n")

    # --- Comments block ---
    comments = metadata.get("comments", "")
    if comments:
        for line in comments.splitlines():
            stripped = line.strip()
            if stripped and not stripped.startswith("#"):
                output.write(f"# {line}\n")
            else:
                output.write(f"{line}\n")
    output.write("# generated by tiled\n")

    # --- Header-end separator (required) ---
    output.write("# -------------\n")

    # --- Column labels line ---
    columns = list(df.columns)
    output.write("# " + " ".join(str(c) for c in columns) + "\n")

    # --- Data section (whitespace-delimited, no index, no header row) ---
    df.to_csv(output, header=False, index=False, sep=" ")

    return output.getvalue().encode()


@default_serialization_registry.register("xdi", "application/x-xdi")
async def serialize_xdi(mimetype, node, metadata, filter_for_access):
    """Serialize an XDI-tagged container node to XDI format.

    The container node is walked to find the first table child, which is read
    as a pandas DataFrame. The XDI header is built from the container's metadata.

    Parameters
    ----------
    mimetype : str
        The requested MIME type (accepted but not used).
    node : container node
        The scan container tagged with Spec("xdi", ...).
    metadata : dict
        The container's metadata dict (must contain XDI fields).
    filter_for_access : callable
        Async callable used to apply access-control filtering when walking the node.

    Returns
    -------
    bytes
        UTF-8 encoded XDI file content.
    """
    # Walk the container to find child nodes after access filtering.
    filtered = await filter_for_access(node)

    # Collect items — support both async items_range and sync items.
    if hasattr(filtered, "items_range"):
        items = await filtered.items_range()
    else:
        items = list(filtered.items())

    if not items:
        raise ValueError(
            "Cannot serialize as XDI: the container node has no child nodes."
        )

    # Find the first table-structured child and read it as a DataFrame.
    df = None
    for _key, child in items:
        if child.structure_family == StructureFamily.table:
            df = await ensure_awaitable(child.read)
            break

    if df is None:
        raise ValueError(
            "Cannot serialize as XDI: no table-structured child found in this container. "
            f"Available child structure families: "
            f"{[child.structure_family for _, child in items]}"
        )

    return _write_xdi(df, metadata)
