database:
  uri: "sqlite+aiosqlite:///./tiled.sqlite"
  init_if_not_exists: true
authentication:
  tiled_admins:
  - provider: toy
    id: "dallan"
  providers:
  - provider: pam
    authenticator: tiled.authenticators:LDAPAuthenticator
    args:
      server_address: "duoproxy.nsls2.bnl.gov"
      bind_dn_template:
      - "BNL\\{username}"
      use_tls: true
      use_ssl: true
      confirmation_message: "You have logged in as {id}."
  - provider: toy
    authenticator: tiled.authenticators:DictionaryAuthenticator
    args:
      users_to_passwords:
        nmaytan: "nmaytan"
        dallan: "dallan"
        biff: "biff"
      confirmation_message: "You have logged in."
access_control:
  access_policy: tag_based_pass_access_policy:TagBasedPASSAccessPolicy
  args:
    provider: "toy"
    tag_config: "tag_definitions.yaml"
    group_parser: tag_based_pass_access_policy:get_group_users
    tags_db: "tags_state.sqlite"
    url: "https://api.nsls2.bnl.gov"
    sync_proposals:
      rate_all: 480    # minutes
      rate_current: 30 # minutes

trees:
  - path: /test/raw
    tree: catalog
    args:
      uri: "sqlite+aiosqlite:///./storage/catalog.db"
      writable_storage: "./storage/data"
      init_if_not_exists: true
      top_level_access_blob: {"tags": ["_ROOT_NODE_SST"]}
