name: Documentation

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
      fail-fast: false

    steps:

    - uses: actions/checkout@v3

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install tiled
      run: uv sync --all-extras

    - name: Build Docs
      shell: bash -l {0}
      run: uv run make -C docs/ html
